name: UPDATE-PULL-REQUEST-PIPELINE

on:
  # push:
  #   branches: [ feature/** ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@master
      # - name: Create feature environment name
      #   id: feature_environment
      #   run: |
      #     FEATURE_BRANCH_NAME=$(echo "$GITHUB_REF" | sed 's:.*/::')
      #     FEATURE_BRANCH_NAME=$(echo "$FEATURE_BRANCH_NAME" | sed 's/./\L&/g')
      #     REPO_ID=$(echo ${{ github.event.repository.id }} | cut -c-5)
      #     FEATURE_ENVIRONMENT="$FEATURE_BRANCH_NAME-$REPO_ID"
      #     echo $FEATURE_ENVIRONMENT
      #     echo "::set-output name=feature_environment::$FEATURE_ENVIRONMENT"

      - name: create-description
        run: "some script for creating PR description from the branch diff"
        id: description
      - name: update-pull-request
        uses: kt3k/update-pr-description@v1.0.1
        with:
          pr_body: ${{ steps.description.outputs.description }}
          destination_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
