name: UPDATE-PULL_REQUEST

on:
  pull_request:
    types: [opened]

env:
  ADMIN_LOGIN_PREFIX: https://www.gat-qa.com/admin/customer-login?featureEnv=
  EXPO_PROJECT_PAGE_PREFIX: https://expo.io/@ef-go-ahead-tours/gat-app?release-channel=

jobs:
  update_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
        id: extract_branch
      - name: Create feature environment name
        id: feature_environment
        run: |
          FEATURE_BRANCH_NAME=$(echo "${{ steps.extract_branch.outputs.branch }}" | sed 's:.*/::')
          FEATURE_BRANCH_NAME=$(echo "$FEATURE_BRANCH_NAME" | sed 's/./\L&/g')
          REPO_ID=$(echo ${{ github.event.repository.id }} | cut -c-5)
          FEATURE_ENVIRONMENT="$FEATURE_BRANCH_NAME-$REPO_ID"
          echo $FEATURE_ENVIRONMENT
          echo "::set-output name=feature_environment::$FEATURE_ENVIRONMENT"
      - id: update_pr
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '[a-z\d-_.\/]+'
          body-update-action: "suffix"
          body-template: |
            - Admin Login: ${{ env.ADMIN_LOGIN_PREFIX }}${{ steps.feature_environment.outputs.feature_environment }}
            - Expo QA: ${{ env.EXPO_PROJECT_PAGE_PREFIX }}${{ steps.feature_environment.outputs.feature_environment }}
