name: UPDATE-PULL_REQUEST

on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    outputs:
      baseMatch: ${{ steps.update_pr.outputs.baseMatch }}
      headMatch: ${{ steps.update_pr.outputs.headMatch }}
      titleUpdated: ${{ steps.update_pr.outputs.titleUpdated }}
      bodyUpdated: ${{ steps.update_pr.outputs.bodyUpdated }}

    steps:
      - name: Create feature environment name
        id: feature_environment
        run: |
          FEATURE_BRANCH_NAME=$(echo "$GITHUB_REF" | sed 's:.*/::')
          FEATURE_BRANCH_NAME=$(echo "$FEATURE_BRANCH_NAME" | sed 's/./\L&/g')
          REPO_ID=$(echo ${{ github.event.repository.id }} | cut -c-5)
          FEATURE_ENVIRONMENT="$FEATURE_BRANCH_NAME-$REPO_ID"
          echo $FEATURE_ENVIRONMENT
          echo "::set-output name=feature_environment::$FEATURE_ENVIRONMENT"
      - id: update_pr
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '[a-z\d-_.\/]+'
          title-template: "[updated-by-action]"
          body-template: |
            ### 💬 Description <br/> _Describe what your PR is trying to accomplish. Add any additional context that might helpful to review_<br/><br/> ### QA Environment <br/> ${{ steps.feature_environment.outputs.feature_environment }}

  update_pr_outputs:
    runs-on: ubuntu-latest
    needs: update_pr
    steps:
      - run: |
          echo 'baseMatch:' ${{needs.update_pr.outputs.baseMatch}}
          echo 'headMatch:' ${{needs.update_pr.outputs.headMatch}}
          echo 'titleUpdated:' ${{needs.update_pr.outputs.titleUpdated}}
          echo 'bodyUpdated:' ${{needs.update_pr.outputs.bodyUpdated}}
