name: UPDATE-PULL_REQUEST

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "SERVICE NAME - Examples: booking | quoting | tour-match | tour-cache"
        required: true

env:
  ADMIN_LOGIN_PREFIX: https://www.gat-qa.com/admin/customer-login?featureEnv=
  EXPO_PROJECT_PAGE_PREFIX: https://expo.io/@ef-go-ahead-tours/gat-app?release-channel=

jobs:
  update_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create feature environment name
        id: feature_environment
        run: |
          FEATURE_BRANCH_NAME=$(echo "$GITHUB_REF" | sed 's:.*/::')
          FEATURE_BRANCH_NAME=$(echo "$FEATURE_BRANCH_NAME" | sed 's/./\L&/g')
          REPO_ID=$(echo ${{ github.event.repository.id }} | cut -c-5)
          FEATURE_ENVIRONMENT="$FEATURE_BRANCH_NAME-$REPO_ID"
          echo $FEATURE_ENVIRONMENT
          echo "::set-output name=feature_environment::$FEATURE_ENVIRONMENT"

      - uses: actions/checkout@master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: update-pull-request
        uses: kt3k/update-pr-description@v1.0.1
        with:
          pr_body: "Admin Login: ${{ env.EXPO_PROJECT_PAGE_PREFIX }}${{ steps.feature_environment.outputs.feature_environment }} - Expo QA: ${{ env.EXPO_PROJECT_PAGE_PREFIX }}${{ steps.feature_environment.outputs.feature_environment }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
